title: "Sara Carvalho"
author: "Sara Carvalho"
description: "ESTGA-UA | NOVA CLUNL | CLLC-UA"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "Home"}
  - {file: "AboutMe.md", title: "About me"}
  - {file: "Publications.md", title: "Publications"}
  - {file: "Projects.md", title: "Projects"}
  - {file: "Activities.md", title: "Other Activities"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:sara.carvalho@ua.pt"}
  - {title: Github, icon: github, url: "https://github.com/sarampcarvalho"}
  - {title: LinkedIn, icon: linkedin, url: "https://https://www.linkedin.com/in/sarampcarvalho/"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/sarampcarvalho"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
